name: Selenium Java Tests

on:
  push:
  pull_request:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || sudo apt-get install -y chromium-browser

      - name: Build project
        run: mvn -B clean install -DskipTests

      - name: Run Selenium Tests
        run: |
          rm -rf /tmp/*
          mvn -B test
